---
sudo: false
env:
  - PERL_LWP_SSL_VERIFY_HOSTNAME=0
cache:
  directories:
    - $HOME/.cpanm
    - $HOME/.nvm
    - $HOME/perl5/perlbrew/perls/5.16/lib
    - /var/tmp
before_install:
  - export HARNESS_OPTIONS=j10:c HARNESS_TIMER=1
install:
  - npm install -g uglify-js handlebars jasmine
  - cpanm --quiet --notest Dist::Zilla
  - dzil authordeps | grep -ve '^\W' | xargs -n 5 -P 10 cpanm --notest --quiet --mirror http://www.cpan.org/ --mirror http://duckpan.org
  - dzil listdeps | grep -ve '^\W' | cpanm --notest --quiet --mirror http://www.cpan.org/ --mirror http://duckpan.org
language: perl
perl:
  - 5.16
script:
  - prove -lr -j1 t
  - jasmine spec/
